version: '3'

services:
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=development
    environment:
      - PORT=3001
      - MONGO_USER=admin
      - MONGO_PASS=admin
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn dev