version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - SERVER_URL=${SERVER_URL}
        - NGINXFILE=${NGINXFILE}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off;'

  server:
    build:
      context: ./server
      args:
        - NODE_ENV=production
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    restart: unless-stopped
    command: yarn start

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    restart: unless-stopped