version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        - SERVER_URL=http://localhost:3001/api/v1
    stdin_open: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: yarn dev

  server:
    build:
      context: ./server
      args:
        - NODE_ENV=development
    environment:
      - PORT=3001
      - MONGO_USER=admin
      - MONGO_PASS=admin
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /app/node_modules
    command: yarn dev