version: '3'

services:
  server:
    build: ./server
    container_name: server
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    driver: local